require_relative "./chess_pieces/rook.rb"
require_relative "./chess_pieces/knight.rb"
require_relative "./chess_pieces/bishop.rb"
require_relative "./chess_pieces/queen.rb"
require_relative "./chess_pieces/king.rb"
require_relative "./chess_pieces/null_piece.rb"
require_relative "./chess_pieces/pawn.rb"
